---
- name: Open SSH-server op Ubuntu
  hosts: all  # Vervang 'your_ubuntu_host' door de naam of het IP-adres van je Ubuntu-machine
  become: yes  # Dit zorgt ervoor dat we root-rechten hebben om de SSH-configuratie te wijzigen

  tasks:
    - name: Installeer openssh-server
      apt:
        name: openssh-server
        state: present  # Zorg ervoor dat openssh-server is geïnstalleerd

    - name: Start en activeer sshd-service
      systemd:
        name: ssh
        state: started
        enabled: yes  # Zorg ervoor dat de sshd-service wordt opgestart bij het opstarten
